# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aiservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61iservice.proto\x12\x0c\x61iservice.v1\"\x1b\n\x0bPromptInput\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x19\n\tFileInput\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"n\n\x0ePredictRequest\x12/\n\x0cprompt_input\x18\x01 \x01(\x0b\x32\x19.aiservice.v1.PromptInput\x12+\n\nfile_input\x18\x02 \x01(\x0b\x32\x17.aiservice.v1.FileInput\"!\n\x0fPredictResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\\\n\x10InferenceService\x12H\n\x07Predict\x12\x1c.aiservice.v1.PredictRequest\x1a\x1d.aiservice.v1.PredictResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROMPTINPUT._serialized_start=33
  _PROMPTINPUT._serialized_end=60
  _FILEINPUT._serialized_start=62
  _FILEINPUT._serialized_end=87
  _PREDICTREQUEST._serialized_start=89
  _PREDICTREQUEST._serialized_end=199
  _PREDICTRESPONSE._serialized_start=201
  _PREDICTRESPONSE._serialized_end=234
  _INFERENCESERVICE._serialized_start=236
  _INFERENCESERVICE._serialized_end=328
# @@protoc_insertion_point(module_scope)
